### ISSUE TITLE
minetest.log overriding causes several crashes

### ISSUE THREAD

**Issue by nonfreegithub** [minetest-go/mtui_mod#6]
https://github.com/minetest-go/mtui_mod/blob/939b1503dc8eb6ee7f6b52dcf14b49842c051623/log_file.lua#L11

This override causes crashes [in MineClone](https://git.minetest.land/MineClone2/MineClone2/issues/3935) and more mods

**Comment by BuckarooBanzay** [comment]
~~i'm very confused as why this should happen:~~

This line checks if 2 parameters are available:
```lua
if type(level) == "string" and type(msg) == "string" then
-- rest omitted
```
if either `level` or `msg` are anything other than of type string it just skips the internal logging (this works even with `nil`)
Afterwards it just delegates to the old `minetest.log` function and even returns the results perfectly.

Maybe it is too early in the morning but i don't see how this particular override should cause an error.
Also: i don't see my code in the stacktrace mentioned :thinking: 

(oh, and: i did test that mod with various games, including mineclone, and i even have one instance currently running without issues)

**EDIT**: nevermind, can reproduce this :/

**Comment by BuckarooBanzay** [comment]
ok, got it: the engine counts the parameters internally and does not check for type, even if it was passed `("msg", nil)` it would default to the 2-param code and fail in it (https://github.com/minetest/minetest/blob/833c32449858c72e1c4ddc2f9306e1f010693c76/src/script/lua_api/l_util.cpp#L53-L82)

Thanks for reporting :+1:

**Comment by nonfreegithub** [comment]
thanks!
