### ISSUE TITLE
MineClone2 crash mesecons lightstone

### ISSUE THREAD

**Issue by nonfreegithub** [minetest-go/mtui_mod#9]
mod version:

master branch commit c55e3fc9d52db78e565b1765db54b10aa87a0367

crash mesecons_lightstone assert failed

**MCL already has a mesecons_lightstone fork** that use differents lightstone nodes ids

```
ERROR[Main]: ModError: Failed to load and run script from /minetest/bin/..mods/mtui_mod/init.lua:                                                                                            
ERROR[Main]: ...minetest/bin/../mods/mtui_mod/mesecons/lightstones.lua:25: assertion failed!            
ERROR[Main]: stack traceback:                                                                             
ERROR[Main]:       [C]: in function 'assert'                                                              
ERROR[Main]:       ...minetest/bin/../mods/mtui_mod/mesecons/lightstones.lua:25: in main chunk          
ERROR[Main]:       [C]: in function 'dofile'                                                              
ERROR[Main]:       ...minetest/bin/../mods/mtui_mod/init.lua:37: in main chunk 
```

**Comment by BuckarooBanzay** [comment]
![facepalm-really](https://github.com/minetest-go/mtui_mod/assets/39065740/b2a69275-f1f4-4f71-be06-8785e17aae14)

>  that use differents lightstone nodes ids

of course, yeah, makes sense....

anyway: where do i find that "fork", searching for "mineclone" and "mesecons" didn't yield anything useful

**Comment by nonfreegithub** [comment]
> where do i find that "fork", searching for "mineclone" and "mesecons" didn't yield anything useful

Here is the [mesecons forks](https://git.minetest.land/MineClone2/MineClone2/src/branch/master/mods/ITEMS/REDSTONE) used by MineClone/MineClonia games

same problem with `mesecons_button` but it dont crash
